# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-11 03:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SuperHero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('real_name', models.CharField(max_length=150)),
                ('strength', models.CharField(max_length=250)),
                ('weapon', models.CharField(max_length=300)),
                ('location', models.CharField(max_length=300)),
                ('universe', models.CharField(choices=[('Marvel', 'Marvel'), ('DC', 'DC'), ('Other', 'Miscellaneous')], max_length=10)),
                ('alive', models.BooleanField(default=True)),
            ],
        ),
    ]
